-- 댓글 테이블
CREATE TABLE FREEBOARD_COMMENT 
(
  COMMENT_NUM Int NOT NULL, 
  COMMENT_BOARD INT  NOT NULL, 
  COMMENT_ID VARCHAR(15), 
  COMMENT_DATE DATE, 
  COMMENT_CONTENT VARCHAR(1000) NOT NULL
 
  CONSTRAINT PK_comment PRIMARY KEY(COMMENT_NUM),
  CONSTRAINT FK_comment FOREIGN KEY(COMMENT_BOARD) REFERENCES MEMBER_BOARD(BOARD_NUM)
);
 
-- MEMBER_BOARD는 게시판 테이블을, BOARD_NUM은 글번호를 나타낸다.
 
-- 댓글 시퀀스 
create sequence COMMENT_SEQ;